version: '3.3'

services:
  db:
    image: mysql:8.0.29
    container_name: todoapp_db
    user: "${UID}"
    environment:
      MYSQL_ROOT_PASSWORD: "p@ssword"
      MYSQL_DATABASE: "todoapp"
    ports:
      - "13306:3306"
    volumes:
      - ./data:/var/lib/mysql
